### ISSUE TITLE
Extracting selected text does not work on macOS

### ISSUE THREAD

**Issue by breitburg** [leanflutter/screen_text_extractor#2]
Hello!

I used example code to test this plugin. Instead of extracting selected text it showed `null`. Seems that there is a problem with simulating <kbd>⌘</kbd> + <kbd>C</kbd> press, because if I try to extract selected text and then manually copy, then it returns copied text.

Issue occurred on macOS 13.0.1 (22A400)

**Comment by imhafeez** [comment]
@breitburg did you find any solution? It doesn't work on macOS

**Comment by breitburg** [comment]
> @breitburg did you find any solution? It doesn't work on macOS

Yes. Giving Accessibility permissions to the app fixed issue for me.

**Comment by imhafeez** [comment]
@breitburg how you can give Accessibility permissions? Any package for permissions to alert user to give that permission?

**Comment by breitburg** [comment]
> @breitburg how you can give Accessibility permissions? Any package for permissions to alert user to give that permission?

There are two methods available in this library: `ScreenTextExtractor.requestAccess()` and `ScreenTextExtractor.isAccessAllowed()`

**Comment by imhafeez** [comment]
I used these. `ScreenTextExtractor.instance.requestAccess()` did nothing. May be because of debug build, I was running direct from vscode. but don't know.

**Comment by breitburg** [comment]
Try to manually give Accessibility permissions in system settings. Also you can try removing App Sandbox from Xcode project. Hope that helps!

**Comment by imhafeez** [comment]
Thanks @breitburg. Let me try that out.

**Comment by 0406445** [comment]
On macos, this is done by simulating duplicate keys, such as in idea, which will not work if the user changes the key
